version: '3.5'
 
services:
    # PHP-FPM
    guestsservice:
        build: .
        restart: always
        tty: true
        working_dir: /var/www/application
        volumes:
            - .:/var/www/application
        container_name: guestsservice
         
    # Nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        tty: true
        environment:
            - "APPLICATION_UPSTREAM=guestsservice:9000"
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/templates/:/etc/nginx/templates/
            - ./public/:/var/www/application/public/
        ports:
            - "80:80"
            - "443:443"

    # MySQL
    mysql:
        image: library/mysql:8.0
        container_name: mysql
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "MYSQL_DATABASE" 
            MYSQL_USER: "MYSQL_USER"
            MYSQL_PASSWORD: "MYSQL_PASSWORD" 
            MYSQL_ROOT_PASSWORD: "MYSQL_ROOT_PASSWORD" 
            SERVICE_NAME: "MYSQL_SERVICE_NAME"
        volumes:
            - mysqlData:/var/lib/mysql
            - mysqlFiles:/var/lib/mysql-files

#Volumes
volumes:
    mysqlData:
        driver: local
    mysqlFiles:
        driver: local